// <auto-generated />
using System;
using EFC;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFC.Migrations
{
    [DbContext(typeof(AppContext))]
    [Migration("20250107202748_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.2");

            modelBuilder.Entity("EFC.Entities.Drink", b =>
                {
                    b.Property<int>("DrinkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AlcoholPercentage")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DrinksMenuId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IncludesUmbrella")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("DrinkId");

                    b.HasIndex("DrinksMenuId");

                    b.ToTable("Drinks");
                });

            modelBuilder.Entity("EFC.Entities.DrinksMenu", b =>
                {
                    b.Property<int>("DrinksMenuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AvailableFrom")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ContainsAlcohol")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("DrinksMenuId");

                    b.ToTable("DrinksMenus");
                });

            modelBuilder.Entity("EFC.Entities.Drink", b =>
                {
                    b.HasOne("EFC.Entities.DrinksMenu", null)
                        .WithMany("Drinks")
                        .HasForeignKey("DrinksMenuId");
                });

            modelBuilder.Entity("EFC.Entities.DrinksMenu", b =>
                {
                    b.Navigation("Drinks");
                });
#pragma warning restore 612, 618
        }
    }
}
